### ISSUE TITLE
reverse proxy

### ISSUE THREAD

**Issue by baha00** [rdegges/okta-express-login-portal#3]
or simlar. How can customize dashboard to actually load different local url, based on user

**Comment by rdegges** [comment]
If you want to build a reverse proxy, you will need to plug something like Okta into your gateway. There are a bunch of different wayts to do this based on the type of proxy you're using (nginx, Mulesoft, Apigee, etc.)

In terms of customizing the dashboard, you can easily do that by just writing some code =) All the stuff I'm showing here is in the source code.
